const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    // //admin
    // ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    // ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    // PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USE_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILDED: 'FETCH_GENDER_FAIDED',

    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILDED: 'FETCH_POSITION_FAILDED',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILDED: 'FETCH_ROLE_FAIDED',

    //luuuser
    CREATE_USER_SUCCSESS: 'CREATE_USER_SUCCSESS',
    CREATE_USER_FAILDED: 'CREATE_USER_FAIDED',

    //alluser
    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILDED: 'FETCH_ALL_USERS_FAIDED',

    //xoauser
    DELETE_USERS_SUCCESS: 'DELETE_USERS_SUCCESS',
    DELETE_USERS_FAILDED: 'DELETE_USERS_FAIDED',

    //edituser
    EDIT_USERS_SUCCESS: 'EDIT_USERS_SUCCESS',
    EDIT_USERS_FAILDED: 'EDIT_USERS_FAIDED',
    ///////////////////////////////
    ///////////danh muc////////////
    ///////////////////////////////
    FETCH_ALL_DANHMUC_SUCCESS: 'FETCH_ALL_DANHMUC_SUCCESS',
    FETCH_ALL_DANHMUC_FAILDED: 'FETCH_ALL_DANHMUC_FAIDED',
    ///luudanhmuc
    CREATE_DANHMUC_SUCCSESS: 'CREATE_DANHMUC_SUCCSESS',
    CREATE_DANHMUC_FAILDED: 'CREATE_DANHMUC_FAIDED',
    //topdanhmuc
    FETCH_TOP_DANHMUC_SUCCESS: 'FETCH_TOP_DANHMUC_SUCCESS',
    FETCH_TOP_DANHMUC_FAILDED: 'FETCH_TOP_DANHMUC_FAIDED',
    ///////////////////////////////
    ///////////loai su kien////////
    ///////////////////////////////
})

export default actionTypes;